---
  deployment:
  tasks:
    - export DEPLOYPATH=/home/sahrialc/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp work.html $DEPLOYPATH
    - /bin/cp work-detail.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp assets/* $DEPLOYPATH